PLATFORM_KEY=linuxdeb
PLATFORM_NAME="DEB Linux (Debian, Ubuntu, Mint, etc.)"
FX_ARCH=linux
INSTALLER_PFX=panopset_
INSTALLER_SFX=_amd64.deb
INSTALLER_XTR="--linux-shortcut --linux-deb-maintainer ${PAN_EMAIL}"
DSPORD=0
LAUNCH_PATH=/opt/panopset/bin/
JAVA_CMD=panopset/flywheel.exe
