PLATFORM_KEY=win
PLATFORM_NAME="Microsoft Windows"
FX_ARCH=win
INSTALLER_PFX=panopset-
INSTALLER_SFX=.msi
INSTALLER_XTR=
DSPORD=2
LAUNCH_PATH="c:\\Program Files\\panopset\\"
JAVA_CMD="panopset\\flywheel.exe"
