# Github project name
GN=panopset/panopset
# Project Artifact Name
PAN=panopset
SPLAPP=flywheel

# ./generateVersion.sh
PV=1.7.0

# Dependencies, also update projects/shoring/$PAN/pom.xml
# kotlin.version
KV=2.4.0
# fx.v
FXV=28-ea+6
# jackson.annotations.version
JA=2.22
# jackson.version
JV=3.2.2
# jsch.version
SV=2.28.7
#slf4j.version
S4=2.0.18
# zt.version
ZT=1.18.2
